### ISSUE TITLE
USB stick printing

### ISSUE THREAD

**Issue by THEb0nny** [fettesps/WanhaoDuplicator4S-Cura#1]
I can't print from a USB stick. I downloaded a plugin from the Cura store for X3G. I save the file to a USB flash drive, but the printer does not print. When the table and the extruder are heated, the printer still stands and does nothing.

Can you tell me?

**Comment by fettesps** [comment]
Are you sure it's just an issue with printing from USB?  Are you able to print fine from an SD card?  Or better yet have you tried using OctoPrint on a Raspberry Pi?  I would try those things to help isolate the problem further.

**Comment by THEb0nny** [comment]
> Are you sure it's just an issue with printing from USB?  Are you able to print fine from an SD card?  Or better yet have you tried using OctoPrint on a Raspberry Pi?  I would try those things to help isolate the problem further.

I put it wrong. By yusb, the printer can only print using another slider, but using a USB flash drive, it does not print.

**Comment by fettesps** [comment]
Sorry, can't help you with that.  I actually removed my SD card reader as it never worked.  As far as USB sticks go there's no way to plug one in on mine, it only has the B style host port on the back for USB which won't accept a USB stick.  So either you've got a different model than me or are mixing up your terminology. I'm not sure what you mean by slider either, sorry!

**Comment by THEb0nny** [comment]
Another person used to print via USB, the file was cut in a replicator slicer. And what I did in the cura slicer, saved in x3g and saved to the SD card, the printer does not print. Do you suggest to install OctoPrint?
